"use client";
import { Providers } from "@/shared/infra/redux/providers";
import "./globals.css";
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { SessionProvider } from "next-auth/react";
import { AntdStyledComponentsRegistry } from "@/shared/infra/antd/AntdStyledComponentsRegistry";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          <Providers>
            <AntdStyledComponentsRegistry>
              {children}
            </AntdStyledComponentsRegistry>
          </Providers>
        </SessionProvider>
      </body>
    </html>
  );
}
